advantageous/qbit

- qbit/core/src/main/java/io/advantageous/qbit/http/client/HttpClient.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpRequestBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/health/HealthServiceImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/util/GzipUtils.java
- qbit/core/src/test/java/io/advantageous/qbit/http/HttpRequestBuilderTest.java
- qbit/web/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/HttpServerVertx.java
- qbit/web/vertx/src/test/java/io/advantageous/qbit/vertx/TestingClientGzipSupport.java
Gzip support added for sending from http client, also fixed bug in builder that would mess up binary send
> Gzip support added for sending from http client, also fixed bug in builder that would mess up binary send

- examples/standalone/src/main/java/io/advantageous/qbit/example/hello/HelloRestClient.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/hello/HelloService.java
- qbit/boon/src/main/java/io/advantageous/qbit/BoonJsonMapper.java
- qbit/cluster/admin/src/main/java/io/advantageous/qbit/meta/swagger/MetaTransformerFromQbitMetaToSwagger.java
- qbit/cluster/admin/src/test/java/io/advantageous/qbit/meta/swagger/SampleService.java
- qbit/core/src/main/java/io/advantageous/qbit/json/JsonMapper.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/ParameterMeta.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/ServiceMethodMeta.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/ParameterMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/RequestMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/ServiceMethodMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/transformer/StandardRequestTransformer.java
- qbit/web/vertx/src/test/java/io/advantageous/qbit/vertx/http/ClientServiceInterface.java
- qbit/web/vertx/src/test/java/io/advantageous/qbit/vertx/http/FullIntegrationTest.java
going to test generation three services: hello, todo, and todo async with swagger.
If they work, then we will merge this pull request.
> Meta data cleanup

- qbit/boon/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/sim/HttpServerSimulator.java
- qbit/boon/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/CollectionArrayUserDefinedObjectRESTTest.java
- qbit/boon/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/PredicateChainTest.java
- qbit/boon/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/SingleArgumentUserDefinedObjectRESTTest.java
- qbit/cluster/admin/src/main/java/io/advantageous/qbit/admin/ManagedServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/Factory.java
- qbit/core/src/main/java/io/advantageous/qbit/http/server/HttpServerBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/http/server/RequestContinuePredicate.java
- qbit/core/src/main/java/io/advantageous/qbit/server/EndPointHealthPredicate.java
- qbit/core/src/main/java/io/advantageous/qbit/server/EndpointServerBuilder.java
- qbit/web/vertx/src/test/java/io/advantageous/qbit/vertx/http/SupportingGetAndPostForSameServicesUnderSameURI.java
see
https://github.com/advantageous/qbit/wiki/%5BDesign-notes%5D-----setShou
ldContinueHttpRequest(Predicate-HttpRequest--predicate) and and
https://github.com/advantageous/qbit/issues/355
> #355 adding chained predicates support

- qbit/admin/src/main/java/io/advantageous/qbit/admin/jobs/JavaStatsCollectorJob.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/ClusteredStatReplicator.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/StatReplicator.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/StatService.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/StatServiceImpl.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/Stats.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/DebugReplicator.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/LocalStatsCollector.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/MinuteStat.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/NoOpReplicator.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/ReplicatorHub.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/StatList.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/StatServiceBuilder.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/StatsDReplicator.java
- qbit/admin/src/test/java/io/advantageous/qbit/StatsMain.java
- qbit/admin/src/test/java/io/advantageous/qbit/metrics/StatServiceImplBundleTest.java
- qbit/admin/src/test/java/io/advantageous/qbit/metrics/StatServiceImplTest.java
- qbit/admin/src/test/java/io/advantageous/qbit/metrics/support/MinuteMeasurementTest.java
- qbit/boon/src/test/java/io/advantageous/qbit/service/ServiceBundleBuilderTest.java
- qbit/core/src/main/java/io/advantageous/qbit/service/stats/StatList.java
- qbit/core/src/main/java/io/advantageous/qbit/service/stats/Stats.java
- qbit/core/src/main/java/io/advantageous/qbit/service/stats/StatsCollector.java
- qbit/core/src/main/java/io/advantageous/qbit/service/stats/StatsCollectorBuffer.java
- qbit/core/src/test/java/io/advantageous/qbit/service/stats/StatsCollectorBufferTest.java
- qbit/spring/src/main/java/io/advantageous/qbit/spring/config/StatsConfiguration.java
Switching over stats service to use longs instead of ints.
> Changed to using longs for stats service

- gradle/wrapper/gradle-wrapper.properties
- qbit/core/src/main/java/io/advantageous/qbit/server/HttpRequestServiceServerHandlerUsingMetaImpl.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxHttpResponseReceiver.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/rest/RestTests.java
Develop fixed issue with Vertx3 port and HttpTextResponse
> Develop fixed issue with Vertx3 port and HttpTextResponse

- qbit/core/src/main/java/io/advantageous/qbit/queue/QueueBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/queue/impl/BasicQueue.java
- qbit/core/src/main/java/io/advantageous/qbit/queue/impl/sender/NoBatchSendQueue.java
- qbit/core/src/test/java/io/advantageous/qbit/queue/impl/sender/NoBatchQueueTest.java
#521 Build queues that are optimized for no batching
> #521 Build queues that are optimized for no batching

- qbit/core/src/main/java/io/advantageous/qbit/annotation/AnnotationConstants.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/HeaderParam.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/PathVariable.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/RequestParam.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/http/GET.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/http/NoCacheHeaders.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/http/ResponseHeader.java
- qbit/core/src/main/java/io/advantageous/qbit/annotation/http/ResponseHeaders.java
- qbit/core/src/main/java/io/advantageous/qbit/http/HttpHeaders.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpRequestBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/RequestMeta.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/ContextMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/RequestMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/ServiceMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/transformer/StandardRequestTransformer.java
- qbit/core/src/main/java/io/advantageous/qbit/server/HttpRequestServiceServerHandlerUsingMetaImpl.java
- qbit/core/src/test/java/io/advantageous/qbit/meta/builder/ServiceMetaBuilderTest.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/services/EmployeeServiceSingleObjectTestService.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/SingleArgumentUserDefinedObjectRESTTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/rest/RestTests.java
https://github.com/advantageous/qbit/issues/540
https://github.com/advantageous/qbit/issues/539 Added more reasonable defaults.
> #540 Add header controls to REST support and NoCache header controls.

- examples/standalone/src/main/resources/logback.xml
- qbit/admin/src/main/java/io/advantageous/qbit/admin/ManagedServiceBuilder.java
- qbit/admin/src/main/java/io/advantageous/qbit/admin/MicroserviceConfig.java
- qbit/core/src/main/java/io/advantageous/qbit/client/BeforeMethodSentChain.java
- qbit/core/src/main/java/io/advantageous/qbit/message/MethodCallBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/message/impl/MethodCallLocal.java
- qbit/core/src/main/java/io/advantageous/qbit/reactive/async/AsyncFutureBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/AfterMethodCallChain.java
- qbit/core/src/main/java/io/advantageous/qbit/service/ServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/BaseServiceQueueImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/ServiceQueueImpl.java
- qbit/core/src/test/java/io/advantageous/qbit/logging/SetupMdcForHttpRequestInterceptorTest.java
> Improve mdc support tests

- examples/standalone/src/main/java/io/advantageous/qbit/example/mda/InternalService.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/mda/InternalServiceImpl.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/mda/RestService.java
- examples/standalone/src/main/resources/logback.xml
- qbit/admin/src/main/java/io/advantageous/qbit/admin/ManagedServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/logging/SetupMdcForHttpRequestInterceptor.java
- qbit/core/src/main/java/io/advantageous/qbit/message/MethodCallBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/message/impl/MethodCallLocal.java
- qbit/core/src/main/java/io/advantageous/qbit/service/health/HealthServiceImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/BaseServiceQueueImpl.java
Finished MDC support
Added examples. Fixed issues.
> Finished MDC support

- qbit/core/src/main/java/io/advantageous/qbit/http/HttpTransport.java
- qbit/core/src/main/java/io/advantageous/qbit/http/server/HttpServer.java
- qbit/core/src/main/java/io/advantageous/qbit/http/server/impl/SimpleHttpServer.java
- qbit/core/src/main/java/io/advantageous/qbit/http/websocket/WebSocket.java
- qbit/core/src/main/java/io/advantageous/qbit/network/impl/NetSocketBase.java
- qbit/core/src/main/java/io/advantageous/qbit/sender/SenderEndPoint.java
- qbit/core/src/main/java/io/advantageous/qbit/server/ServiceEndpointServer.java
- qbit/core/src/main/java/io/advantageous/qbit/server/ServiceEndpointServerImpl.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/client/HttpVertxClient.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/HttpServerVertx.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxServerUtils.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/TestHeaderFidelity.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/TestingClientGzipSupport.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/VertxIntegrationSimpleHttpRouterAndRouteTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/VertxIntegrationSimpleHttpRouterTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/VertxIntegrationSimpleHttpTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/VertxRESTIntegrationTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/FullIntegrationTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/HttpClientVertxTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/LeakTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/LoadTestingTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/SupportingGetAndPostForSameServicesUnderSameURI.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/rest/RestTests.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/websocket/WebSocketTest.java
> #560 Fixed sending WebSocket Binary

- qbit/core/src/main/java/io/advantageous/qbit/meta/builder/ContextMetaBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/meta/provider/StandardMetaDataProvider.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/services/EmployeeServiceCollectionTestService.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/services/HRService.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/services/MyService.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/sim/HttpServerSimulator.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/SingleArgumentUserDefinedObjectRESTTest.java
https://github.com/advantageous/qbit/issues/250
> #250 FIXED Brittle pathing

- examples/standalone/build.gradle
- examples/standalone/src/main/java/io/advantageous/qbit/example/event.bus/EventExampleService.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/event.bus/MyEvent.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/event.bus/SecondEventExample.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/event.bus/ThirdEventExample.java
- qbit/admin/src/main/java/io/advantageous/qbit/admin/ManagedServiceBuilder.java
- qbit/eventbus-replicator/src/main/java/io/advantageous/qbit/eventbus/EventBusCluster.java
> #484 remote event bus example

- examples/standalone/src/main/java/io/advantageous/qbit/example/nocache/NoCacheService.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpResponseDecorator.java
- qbit/core/src/main/java/io/advantageous/qbit/server/HttpRequestServiceServerHandlerUsingMetaImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/util/MultiMap.java
- qbit/core/src/main/java/io/advantageous/qbit/util/MultiMapImpl.java
- qbit/servlet/src/main/java/io/advantageous/qbit/servlet/HttpServletHeaderMultiMap.java
- qbit/servlet/src/main/java/io/advantageous/qbit/servlet/HttpServletParamMultiMap.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/MultiMapWrapper.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxHttpResponseReceiver.java
https://github.com/advantageous/qbit/issues/576
> https://github.com/advantageous/qbit/issues/576

- qbit/core/src/main/java/io/advantageous/qbit/logging/SetupMdcForHttpRequestInterceptor.java
https://github.com/advantageous/qbit/issues/570
> https://github.com/advantageous/qbit/issues/570

- examples/standalone/src/main/java/io/advantageous/qbit/example/perf/Main.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/LocalStatsCollectorBuilder.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/StatServiceBuilder.java
- qbit/admin/src/main/java/io/advantageous/qbit/metrics/support/StatsDReplicatorBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/boon/events/impl/BoonEventManager.java
- qbit/core/src/main/java/io/advantageous/qbit/boon/service/impl/BoonServiceMethodCallHandler.java
- qbit/core/src/main/java/io/advantageous/qbit/events/EventManager.java
- qbit/core/src/main/java/io/advantageous/qbit/kvstore/LocalKeyValueStoreServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/kvstore/lowlevel/LowLevelLocalKeyValueStoreServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/proxy/ProxyBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/queue/impl/BasicQueue.java
- qbit/core/src/main/java/io/advantageous/qbit/queue/impl/BasicReceiveQueue.java
- qbit/core/src/main/java/io/advantageous/qbit/queue/impl/sender/AbstractBasicSendQueue.java
- qbit/core/src/main/java/io/advantageous/qbit/service/ServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/ServiceContext.java
- qbit/core/src/main/java/io/advantageous/qbit/service/ServiceMethodHandler.java
- qbit/core/src/main/java/io/advantageous/qbit/service/ServiceQueue.java
- qbit/core/src/main/java/io/advantageous/qbit/service/dispatchers/RoundRobinServiceWorkerBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/dispatchers/ShardedServiceWorkerBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/health/HealthServiceBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/BaseServiceQueueImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/CallbackManagerWithTimeout.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/ServiceQueueImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/system/QBitSystemManager.java
- qbit/core/src/test/java/io/advantageous/qbit/events/EventManagerBuilderTest.java
- qbit/core/src/test/java/io/advantageous/qbit/events/SendingEventsUsingLooselyTypeChannelTest.java
- qbit/core/src/test/java/io/advantageous/qbit/events/SendingEventsUsingStronglyTypedChannelToServiceTest.java
- qbit/core/src/test/java/io/advantageous/qbit/kvstore/LocalKeyValueStoreServiceTest.java
> #583 and a few others, perf testing, cleanup.

- examples/standalone/src/main/java/io/advantageous/qbit/example/form/FormSubmit.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/perf/Main.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpRequest.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpRequestBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/BaseServiceQueueImpl.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/HttpServerVertx.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxServerUtils.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/HttpClientVertxTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/rest/RestTests.java
formParams, perf improvements, bug fixes
> formParams, perf improvements, bug fixes

- build.gradle
- qbit/core/src/test/java/io/advantageous/qbit/boon/spi/BoonJsonMapperTest.java
https://github.com/advantageous/qbit/issues/589
https://github.com/advantageous/boon/issues/7
> https://github.com/advantageous/qbit/issues/589

- examples/standalone/src/main/java/io/advantageous/qbit/example/perf/Main.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/perf/QueuePerfMain.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/rest/RestService.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/service/ServiceBundleMain.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/service/ServiceMain.java
- qbit/build.gradle
- qbit/core/src/main/java/io/advantageous/qbit/boon/service/impl/BoonServiceMethodCallHandler.java
- qbit/core/src/main/java/io/advantageous/qbit/queue/impl/sender/AbstractBasicSendQueue.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/BaseServiceQueueImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/CallbackManagerWithTimeout.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/HandlerKey.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/ServiceBundleImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/stream/QueueToStreamRoundRobin.java
- qbit/core/src/main/java/io/advantageous/qbit/stream/QueueToStreamUnicast.java
- qbit/core/src/test/java/io/advantageous/qbit/proxy/ServiceProxyFactoryTest.java
- qbit/core/src/test/java/io/advantageous/qbit/stream/QueueToStreamMulticast.java
- qbit/core/src/test/java/io/advantageous/qbit/stream/QueueToStreamUnicastTest.java
> Reactive streams

- examples/standalone/src/main/java/io/advantageous/qbit/example/nocache/NoCacheService.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/rest/RestService.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpResponseCreator.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpResponseReceiver.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/decorator/HttpResponseDecorator.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/impl/HttpResponseCreatorDefault.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/sim/HttpServerSimulator.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/PredicateChainTest.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxHttpResponseReceiver.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxServerUtils.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/SupportingGetAndPostForSameServicesUnderSameURI.java
First attempt to add HTTP method to HTTP response decorator
> First attempt to add HTTP method to HTTP response decorator

- qbit/core/src/main/java/io/advantageous/qbit/Factory.java
- qbit/core/src/main/java/io/advantageous/qbit/QBit.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpRequest.java
- qbit/core/src/main/java/io/advantageous/qbit/http/request/HttpRequestBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/http/server/HttpServerBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/http/server/impl/SimpleHttpServer.java
- qbit/core/src/main/java/io/advantageous/qbit/spi/HttpServerFactory.java
- qbit/core/src/test/java/io/advantageous/qbit/http/HttpServerBuilderTest.java
- qbit/core/src/test/java/io/advantageous/qbit/perf/PerfTestMain.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/CollectionArrayUserDefinedObjectRESTTest.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/PredicateChainTest.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/ResourceStyleRestServiceTest.java
- qbit/core/src/test/java/io/advantageous/qbit/service/rest/endpoint/tests/tests/SingleArgumentUserDefinedObjectRESTTest.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/VertxHttpServerBuilder.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/HttpServerVertx.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/HttpServerVertxFactory.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/SimpleVertxHttpServerWrapper.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/http/server/VertxServerUtils.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/VertxIntegrationSimpleHttpTest.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/http/HttpClientVertxTest.java
Ability to add filters body size for size.
https://github.com/advantageous/qbit/issues/620
> Ability to add filters for size.

- .gitignore
- qbit/core/src/main/java/io/advantageous/qbit/message/MethodCall.java
- qbit/core/src/main/java/io/advantageous/qbit/message/MethodCallBuilder.java
- qbit/core/src/main/java/io/advantageous/qbit/message/impl/MethodCallImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/message/impl/MethodCallLocal.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/BaseServiceQueueImpl.java
- qbit/core/src/main/java/io/advantageous/qbit/service/impl/CallbackManagerWithTimeout.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridge.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridgeBuilder.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridgeTest.java
Improve callback dispatch to support N number of gateways.
> Improve callback dispatch to support N number of gateways

- examples/standalone/src/main/javascript/testClient.js
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridge.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridgeTest.java
Reviewed and agreed upon a change.
> Reviewed and agreed upon a change.

- examples/standalone/src/main/java/io/advantageous/qbit/example/vertx/eventbus/bridge/EmployeeService.java
- examples/standalone/src/main/java/io/advantageous/qbit/example/vertx/eventbus/bridge/EventBusBridgeExample.java
- examples/standalone/src/main/javascript/testClient.js
- qbit/core/src/main/java/io/advantageous/qbit/meta/transformer/StandardRequestTransformer.java
- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridge.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridgeTest.java
> Avoid double parse json

- qbit/vertx/src/main/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridge.java
- qbit/vertx/src/test/java/io/advantageous/qbit/vertx/eventbus/bridge/VertxEventBusBridgeTest.java
> Integration

- build.gradle
- qbit/build.gradle
- qbit/core/src/main/java/io/advantageous/qbit/reactive/Callback.java
- qbit/core/src/main/java/io/advantageous/qbit/reactive/Reactor.java
- qbit/core/src/main/java/io/advantageous/qbit/reakt/Reakt.java
- qbit/core/src/main/java/io/advantageous/qbit/service/discovery/ServiceDiscovery.java
- qbit/core/src/main/java/io/advantageous/qbit/service/discovery/impl/ServiceDiscoveryImpl.java
- qbit/core/src/test/java/io/advantageous/qbit/reakt/ReaktTest.java
> Integration - using Reakt

- qbit/consul-client/src/main/java/io/advantageous/consul/Consul.java
- qbit/consul-client/src/main/java/io/advantageous/consul/domain/Session.java
- qbit/consul-client/src/main/java/io/advantageous/consul/domain/SessionBehavior.java
- qbit/consul-client/src/main/java/io/advantageous/consul/domain/SessionId.java
- qbit/consul-client/src/main/java/io/advantageous/consul/endpoints/KeyValueStoreEndpoint.java
- qbit/consul-client/src/main/java/io/advantageous/consul/endpoints/RequestUtils.java
- qbit/consul-client/src/main/java/io/advantageous/consul/endpoints/SessionEndpoint.java
- qbit/consul-client/src/test/java/io/advantageous/consul/AgentEndpointTest.java
- qbit/consul-client/src/test/java/io/advantageous/consul/ConsulServiceDiscoveryTest.java
- qbit/consul-client/src/test/java/io/advantageous/consul/endpoints/SessionEndpointTest.java
- qbit/core/src/main/java/io/advantageous/qbit/http/HTTP.java
> Add session support to consul

- qbit/consul-client/src/main/java/io/advantageous/consul/domain/Service.java
- qbit/consul-client/src/test/java/io/advantageous/consul/ConsulServiceDiscoveryTest.java
- qbit/core/src/main/java/io/advantageous/qbit/service/discovery/ServiceDiscovery.java
- qbit/core/src/main/java/io/advantageous/qbit/service/discovery/impl/ServiceDiscoveryImpl.java
Fix host type which is a string :)
> Fix incorrect type for host
